name: A workflow to OPA validate Harness pipline YAML
on: push
  paths:
    - './pipelines/*.yaml'
jobs:
  build:
    name: OPA Validate Harness Pipline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          tests: "./rego"
          options: "--verbose"
